export const APP_SHELL_GLOBAL_HEADER_LAYER_CLASS = "z-[42]";
export const APP_SHELL_RIGHT_PANEL_LAYER_CLASS = "z-[41]";
export const APP_SHELL_RIGHT_PANEL_COMPOSER_OVERLAY_LAYER_CLASS = "z-[42]";
export const APP_SHELL_FLOATING_UI_LAYER_CLASS = "z-50";
