export type {
  Priority,
  Estimate,
  CardStatus,
  Card,
  CardRunInTarget,
  Column,
  Board,
  CanvasData,
  ClipboardPasteInspectionResult,
  CardInput,
  CardCreateInput,
  CardUpdateResult,
  CardCreatePlacement,
  CalendarOccurrence,
  CardOccurrenceActionInput,
  CardOccurrenceUpdateInput,
  OccurrenceActionSource,
  OccurrenceEditScope,
  MoveCardInput,
  MoveCardToProjectInput,
  MoveCardToProjectResult,
  MoveCardsInput,
  BlockDropImportInput,
  BlockDropImportResult,
  BlockDropImportSourceUpdate,
  CardDropMoveToEditorInput,
  CardDropMoveToEditorResult,
  RecurrenceConfig,
  RecurrenceEndCondition,
  RecurrenceFrequency,
  ReminderConfig,
  OccurrenceTimingUpdates,
  Project,
  ProjectInput,
  ProjectSession,
  ProjectSessionCreateInput,
  ProjectSessionDbView,
  ProjectSessionForkInput,
  ProjectSessionForkResult,
  ProjectSessionListOptions,
  ProjectSessionPinnedInput,
  ProjectSessionPinnedOrderInput,
  ProjectSessionTab,
  ProjectSessionTabConfig,
  ProjectSessionTabCreateInput,
  ProjectSessionTabDeleteInput,
  ProjectSessionTabKind,
  ProjectSessionTabUpdateInput,
  ProjectSessionThreadLink,
  ProjectSessionThreadLinkInput,
  ProjectSessionUnreadInput,
  ProjectSessionUpdateInput,
  PanelId,
  ProjectSessionPanelLayout,
  ProjectSessionPanelState,
  ProjectSessionPanelNode,
  ProjectSessionPanelSplitSide,
  ProjectSessionSplitBranch,
  ProjectSessionSplitLeaf,
  CodexConnectionState,
  CodexAccountSnapshot,
  CodexDictationStateSnapshot,
  CodexModelOption,
  CodexCollaborationModeKind,
  CodexCollaborationModeState,
  CodexCollaborationModePreset,
  CodexRateLimitsSnapshot,
  CodexReasoningEffort,
  CodexReasoningEffortOption,
  CodexServiceTier,
  CodexThreadDetailLevel,
  CodexThreadSettings,
  CodexThreadStartForCardInput,
  CodexThreadStartForSessionInput,
  CodexSideChatStartInput,
  CodexSideChatStartResult,
  CodexTurnStartOptions,
  CodexPromptAgentConfigInput,
  CodexPromptImageInput,
  CodexPromptInput,
  CodexSteerTurnInput,
  CodexSteeringStatus,
  CodexUserAttachment,
  CodexUserFileAttachment,
  CodexUserImageAttachment,
  CodexPermissionMode,
  CodexPermissionState,
  CodexThreadSummary,
  CodexThreadDetail,
  CodexConversationItem,
  CodexConversationTurn,
  CodexConversationServerRequest,
  CodexConversationLiveRequest,
  CodexConversationSource,
  CodexConversationResumeState,
  CodexConversationSnapshot,
  CodexThreadStatusType,
  CodexThreadActiveFlag,
  CodexThreadStreamStateChange,
  CodexConversationStateUpdate,
  CodexSharedObject,
  CodexPendingSteer,
  CodexQueuedFollowUp,
  CodexBackgroundTerminalRow,
  CodexConversationChildMembership,
  CodexConversationCapabilityFlags,
  CodexComposerIntent,
  CodexThreadTokenUsage,
  CodexThreadActionResult,
  CodexTokenUsageBreakdown,
  CodexTurnSummary,
  CodexThreadStartProgressPhase,
  CodexItemNormalizedKind,
  CodexSemanticItemKind,
  CodexItemStatus,
  CodexTranscriptEntryKind,
  CodexTranscriptEntryStatus,
  CodexTranscriptEntrySource,
  CodexTranscriptEntry,
  CodexToolCallSubtype,
  CodexToolCallView,
  CodexMcpToolCallInvocation,
  CodexMcpToolCallContentBlock,
  CodexMcpToolCallNormalizedResult,
  CodexMcpToolCallView,
  CodexCommandAction,
  CodexFileChange,
  CodexFileChangeView,
  CodexItemView,
  CodexTurnDiffReviewTarget,
  CodexApprovalRequest,
  CodexApprovalDecision,
  CodexUserInputRequest,
  CodexPlanImplementationRequest,
  CodexMcpServerElicitationRequest,
  CodexMcpServerElicitationAction,
  CodexPendingThreadRequest,
  CodexEvent,
  CodexHostMessage,
  CodexReviewStartParams,
  CodexReviewStartResponse,
  CodexReviewTarget,
  BranchDiffStatsRequest,
  BranchDiffStatsResult,
  GitReviewFileStatus,
  GitReviewFileSummary,
  GitReviewFileContents,
  GitReviewFileContentsInput,
  GitReviewSearchInput,
  GitReviewSearchResult,
  GitMergeBaseRequest,
  GitMergeBaseResult,
  GitApplyPatchInput,
  GitApplyPatchResult,
  GitApplyPatchStatus,
  GitApplyPatchTarget,
  GitReviewSnapshot,
  GitReviewSource,
  ReviewDiffEntry,
  ReviewDiffFilter,
  ReviewDiffLoadStatus,
  ReviewDiffRequest,
  ReviewDiffResult,
  BackupRecord,
  BackupSettings,
  BackupSettingsEnvOverrides,
  HistorySettings,
  HistorySettingsEnvOverrides,
  ThreadNotificationTurnMode,
  ThreadNotificationSettings,
  DesktopNotificationAction,
  DesktopNotificationActionPayload,
  DesktopNotificationKind,
  DesktopNotificationPayload,
  AppUpdateSettings,
  UpdateAppUpdateSettingsInput,
  AppUpdateStatus,
  AppUpdateStatusKind,
  CreateBackupInput,
  RestoreBackupInput,
  RestoreBackupResult,
  ManagedWorktreeRecord,
  WorktreeEnvironmentOption,
  WorktreeEnvironmentPlatform,
  WorktreeEnvironmentActionIcon,
  WorktreeEnvironmentActionDefinition,
  WorktreeEnvironmentScriptDefinition,
  WorktreeEnvironmentDefinition,
  WorktreeEnvironmentConfigState,
  WorktreeEnvironmentConfigRecord,
  WorktreeEnvironmentSettingsSnapshot,
  UpdateWorktreeEnvironmentConfigInput,
  WorktreeStartMode,
  UpdateBackupSettingsInput,
  UpdateHistorySettingsInput,
  UpdateThreadNotificationSettingsInput,
  UploadedResourceAsset,
} from "../../shared/types";

export { PROJECT_SESSION_SINGLETON_TAB_KINDS } from "../../shared/types";

export type {
  WorkbenchLayoutCardStageState,
  WorkbenchLayoutFilesStageTab,
  WorkbenchRecentCardSession,
  WorkbenchLayoutStageId,
  WorkbenchLayoutStageNavDirection,
  WorkbenchLayoutSnapshot,
  WorkbenchLayoutThreadsStageTab,
  WorkbenchLayoutView,
} from "../../shared/workbench-layout";
export type {
  UpdateWindowRestoreSettingsInput,
  WindowRestorePolicy,
  WindowRestoreSettings,
  WindowSessionBootstrap,
  WindowSessionBounds,
  WindowSessionCatalog,
  WindowSessionRecord,
  WindowSessionSeed,
} from "../../shared/window-session";

import type { Estimate, CardUpdateResult } from "../../shared/types";

export const estimateStyles: Record<Estimate, { label: string; className: string }> = {
  xl: { label: "XL", className: "bg-[var(--red-bg)] text-[var(--red-text)]" },
  l: { label: "L", className: "bg-[var(--orange-bg)] text-[var(--orange-text)]" },
  m: { label: "M", className: "bg-[var(--yellow-bg)] text-[var(--yellow-text)]" },
  s: { label: "S", className: "bg-[var(--green-bg)] text-[var(--green-text)]" },
  xs: { label: "XS", className: "bg-[var(--blue-bg)] text-[var(--blue-text)]" },
};

export const estimateOptions: Array<{ value: "none" | Estimate; label: string }> = [
  { value: "none", label: "None" },
  ...Object.entries(estimateStyles).map(([value, { label }]) => ({
    value: value as Estimate,
    label,
  })),
];

export type CardUpdateMutationResult = CardUpdateResult | {
  status: "error";
  error: string;
};
