import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, expect, test } from "vitest";
import {
  checkWorktreeReleaseTransition,
  detectReleaseTransition,
  inspectReleaseSource,
  prepareReleaseSource,
} from "./source";

const PACKAGE_NAMES = [
  "nodex-browser-profile-helper",
  "nodex-cli",
  "nodex-core",
  "nodex-core-contracts",
  "nodex-core-protocol",
  "nodex-core-server",
] as const;

let fixture = "";

const git = (...args: string[]): string =>
  execFileSync("git", args, {
    cwd: fixture,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();

const writeFixture = (version = "0.1.10"): void => {
  writeFileSync(
    join(fixture, "package.json"),
    `${JSON.stringify({ name: "nodex", version }, null, 2)}\n`,
  );
  writeFileSync(
    join(fixture, "Cargo.toml"),
    `[workspace]\nmembers = []\n\n[workspace.package]\nversion = "${version}"\n`,
  );
  writeFileSync(
    join(fixture, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n${PACKAGE_NAMES.map(
      (name) => `[[package]]\nname = "${name}"\nversion = "${version}"\n`,
    ).join("\n")}`,
  );
  writeFileSync(
    join(fixture, "CHANGELOG.md"),
    `# Changelog\n\n## [Unreleased]\n\n### Added\n- Added a verified release flow.\n\n## [${version}] - 2026-05-03\n\n### Added\n- Previous release.\n`,
  );
};

beforeEach(() => {
  fixture = mkdtempSync(join(tmpdir(), "nodex-release-source-"));
  writeFixture();
  git("init");
  git("config", "user.name", "Nodex Test");
  git("config", "user.email", "nodex@example.com");
  git("add", ".");
  git("commit", "-m", "chore: seed release source");
});

afterEach(() => rmSync(fixture, { recursive: true, force: true }));

test("prepareReleaseSource synchronizes package, Cargo, lock, and changelog without committing", () => {
  const prepared = prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  const snapshot = inspectReleaseSource(fixture);

  expect(prepared).toMatchObject({ tag: "v0.2.0", version: "0.2.0" });
  expect(snapshot.packageVersion).toBe("0.2.0");
  expect(snapshot.cargoVersion).toBe("0.2.0");
  expect(snapshot.changelog).toContain("## [0.2.0] - 2026-07-31");
  expect(git("log", "-1", "--format=%s")).toBe("chore: seed release source");
  expect(git("diff", "--name-only").split("\n").sort()).toEqual([
    "CHANGELOG.md",
    "Cargo.lock",
    "Cargo.toml",
    "package.json",
  ]);
});

test("checkWorktreeReleaseTransition accepts exactly the metadata-only release diff", () => {
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  expect(checkWorktreeReleaseTransition(fixture, "HEAD")).toMatchObject({
    baseVersion: "0.1.10",
    shouldRelease: true,
    tag: "v0.2.0",
    version: "0.2.0",
  });
});

test("detectReleaseTransition ignores an identity repair without an app version change", () => {
  writeFileSync(join(fixture, "README.md"), "documentation\n");
  git("add", "README.md");
  git("commit", "-m", "docs: add readme");
  expect(detectReleaseTransition(fixture, "HEAD^", "HEAD")).toEqual({
    shouldRelease: false,
    version: "0.1.10",
  });
});

test("release transition rejects source changes mixed into the metadata commit", () => {
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  writeFileSync(join(fixture, "README.md"), "mixed source change\n");
  expect(() => checkWorktreeReleaseTransition(fixture, "HEAD")).toThrow("may change only");
});

test("release preparation rejects a dirty worktree before writing", () => {
  writeFileSync(
    join(fixture, "CHANGELOG.md"),
    `${readFileSync(join(fixture, "CHANGELOG.md"), "utf8")}dirty\n`,
  );
  expect(() =>
    prepareReleaseSource({
      cwd: fixture,
      date: "2026-07-31",
      validateCargoMetadata: false,
      version: "0.2.0",
    }),
  ).toThrow("clean git worktree");
});
