import { describe, expect, it } from "vite-plus/test";
import type { WorktreeEnvironmentDefinition } from "../../shared/types";
import {
  parseWorktreeEnvironmentToml,
  serializeWorktreeEnvironmentDefinition,
  WORKTREE_ENVIRONMENT_ACTION_MAX_COUNT,
  WORKTREE_ENVIRONMENT_ACTION_NAME_MAX_CHARS,
  WORKTREE_ENVIRONMENT_SCRIPT_MAX_BYTES,
} from "./worktree-environment-codec";

function makeEnvironment(
  overrides: Partial<WorktreeEnvironmentDefinition> = {},
): WorktreeEnvironmentDefinition {
  return {
    version: 1,
    name: "Example",
    setup: { script: null, platformScripts: {} },
    cleanup: { script: null, platformScripts: {} },
    actions: [],
    ...overrides,
  };
}

describe("worktree environment codec", () => {
  it("writes the exact minimal byte contract", () => {
    expect(serializeWorktreeEnvironmentDefinition(makeEnvironment())).toBe(
      [
        "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY",
        "version = 1",
        'name = "Example"',
        "",
        "[setup]",
        'script = ""',
        "",
      ].join("\n"),
    );
  });

  it("writes lifecycle platforms, cleanup, and actions in stable order", () => {
    expect(
      serializeWorktreeEnvironmentDefinition(
        makeEnvironment({
          setup: {
            script: "default",
            platformScripts: {
              win32: "windows",
              darwin: "mac",
              linux: "linux",
            },
          },
          cleanup: {
            script: null,
            platformScripts: { linux: "clean" },
          },
          actions: [
            { name: " Run ", icon: null, command: " npm run dev ", platform: null },
            { name: "Test", icon: "test", command: "pnpm test", platform: "linux" },
          ],
        }),
      ),
    ).toBe(
      [
        "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY",
        "version = 1",
        'name = "Example"',
        "",
        "[setup]",
        'script = "default"',
        "",
        "[setup.darwin]",
        'script = "mac"',
        "",
        "[setup.linux]",
        'script = "linux"',
        "",
        "[setup.win32]",
        'script = "windows"',
        "",
        "[cleanup]",
        'script = ""',
        "",
        "[cleanup.linux]",
        'script = "clean"',
        "",
        "[[actions]]",
        'name = "Run"',
        'command = "npm run dev"',
        "",
        "[[actions]]",
        'name = "Test"',
        'icon = "test"',
        'command = "pnpm test"',
        'platform = "linux"',
        "",
      ].join("\n"),
    );
  });

  it("filters blank and incomplete actions from serialized bytes", () => {
    const raw = serializeWorktreeEnvironmentDefinition(
      makeEnvironment({
        actions: [
          { name: "", icon: "tool", command: "", platform: null },
          { name: "Named", icon: "run", command: "", platform: null },
          { name: "", icon: "test", command: "command", platform: "darwin" },
        ],
      }),
    );

    expect(raw).toBe(serializeWorktreeEnvironmentDefinition(makeEnvironment()));
  });

  it("normalizes line endings and round-trips multiline delimiters and slashes", () => {
    const script = "first\r\ncontains ''' and \\\\ path\rand \"\"\" too";
    const raw = serializeWorktreeEnvironmentDefinition(
      makeEnvironment({
        setup: { script, platformScripts: {} },
      }),
    );
    const parsed = parseWorktreeEnvironmentToml(
      raw,
      "/workspace/.codex/environments/environment.toml",
    );

    expect(parsed.setup.script).toBe("first\ncontains ''' and \\\\ path\nand \"\"\" too");
    expect(raw.endsWith("\n")).toBe(true);
    expect(raw.endsWith("\n\n")).toBe(false);
  });

  it("requires the reference schema while filtering malformed actions", () => {
    expect(() => parseWorktreeEnvironmentToml('name = "Missing setup"\n', "/tmp/a.toml")).toThrow(
      "setup is required",
    );
    expect(() =>
      parseWorktreeEnvironmentToml(
        'version = 0\nname = "Bad"\n[setup]\nscript = ""\n',
        "/tmp/a.toml",
      ),
    ).toThrow("version must be a positive integer");
    expect(() =>
      parseWorktreeEnvironmentToml(
        'name = "Bad"\n[setup]\nscript = ""\n[[actions]]\nname = "Run"\ncommand = "go"\nplatform = "other"\n',
        "/tmp/a.toml",
      ),
    ).toThrow("Action platform");

    const parsed = parseWorktreeEnvironmentToml(
      [
        'name = " Trimmed "',
        "[setup]",
        'script = " setup "',
        "[[actions]]",
        'name = " "',
        'command = "ignored"',
        "[[actions]]",
        'name = " Run "',
        'command = " npm run dev "',
        "",
      ].join("\n"),
      "/tmp/a.toml",
    );

    expect(parsed.name).toBe("Trimmed");
    expect(parsed.setup.script).toBe("setup");
    expect(parsed.actions).toEqual([
      {
        name: "Run",
        icon: null,
        command: "npm run dev",
        platform: null,
      },
    ]);
  });

  it("enforces field and aggregate limits", () => {
    expect(() =>
      serializeWorktreeEnvironmentDefinition(
        makeEnvironment({
          setup: {
            script: "x".repeat(WORKTREE_ENVIRONMENT_SCRIPT_MAX_BYTES + 1),
            platformScripts: {},
          },
        }),
      ),
    ).toThrow("Setup script");
    expect(() =>
      serializeWorktreeEnvironmentDefinition(
        makeEnvironment({
          actions: [
            {
              name: "x".repeat(WORKTREE_ENVIRONMENT_ACTION_NAME_MAX_CHARS + 1),
              icon: null,
              command: "run",
              platform: null,
            },
          ],
        }),
      ),
    ).toThrow("Action 1 name");
    expect(() =>
      serializeWorktreeEnvironmentDefinition(
        makeEnvironment({
          actions: Array.from(
            { length: WORKTREE_ENVIRONMENT_ACTION_MAX_COUNT + 1 },
            (_, index) => ({
              name: `Action ${index}`,
              icon: null,
              command: "run",
              platform: null,
            }),
          ),
        }),
      ),
    ).toThrow("at most 100 actions");
  });
});
