/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/core/v1/admin/shutdown": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["shutdown"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["events"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/handshake": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["handshake"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["health"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/administration/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["administration_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/administration/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["administration_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/automation/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["automation_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/automation/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["automation_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/database/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["database_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/database/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["database_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/document/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["document_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/document/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["document_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/library/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["library_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/library/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["library_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/workspace/apply": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["workspace_apply"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/core/v1/modules/workspace/read": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["workspace_read"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AutomationApplyRequest: components["schemas"]["ModuleApplyRequest_AutomationIntent"];
        readonly AutomationApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_AutomationCommitValue_AutomationReceipt"];
        readonly AutomationEvent: {
            readonly automation_ids: readonly string[];
            readonly kind: components["schemas"]["AutomationEventKind"];
            readonly lease_ids: readonly string[];
            readonly occurrence_ids: readonly string[];
        };
        /** @enum {string} */
        readonly AutomationEventKind: "automation_changed";
        readonly AutomationLease: {
            /** Format: int32 */
            readonly attempt: number;
            readonly automation_id: string;
            readonly expires_at: string;
            readonly lease_id: string;
        };
        readonly AutomationReadRequest: components["schemas"]["ModuleReadRequest_AutomationRead"];
        readonly AutomationReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_AutomationReadValue"];
        readonly BackupRecord: {
            readonly backup_id: string;
            /** Format: int64 */
            readonly byte_length: number;
            readonly created_at: string;
            readonly label?: string | null;
        };
        readonly ClientIdentity: {
            readonly build_id: string;
            readonly kind: components["schemas"]["ClientKind"];
        };
        /** @enum {string} */
        readonly ClientKind: "electron_host" | "native_cli" | "test";
        readonly CommittedCoreModuleEvent: {
            readonly committed_at: string;
            readonly operation_id?: string | null;
            readonly payload: components["schemas"]["CoreModuleEventPayload"];
            /** Format: int64 */
            readonly sequence: number;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly CoreError: {
            readonly code: components["schemas"]["CoreErrorCode"];
            readonly message: string;
            readonly recovery: components["schemas"]["CoreErrorRecovery"];
            readonly retryable: boolean;
        };
        /** @enum {string} */
        readonly CoreErrorCode: "invalid_input" | "unauthorized" | "not_found" | "ambiguous" | "stale_store_epoch" | "revision_conflict" | "generation_conflict" | "head_conflict" | "idempotency_key_reused" | "document_update_missing_dependencies" | "invalid_document_schema" | "maintenance_in_progress" | "schema_unsupported" | "store_corrupt" | "protocol_incompatible" | "event_replay_unavailable" | "core_unavailable";
        readonly CoreErrorRecovery: {
            /** @enum {string} */
            readonly kind: "none";
        } | {
            /** @enum {string} */
            readonly kind: "current_store_epoch";
            readonly store_epoch: components["schemas"]["StoreEpoch"];
        } | {
            /** @enum {string} */
            readonly kind: "current_revision";
            /** Format: int64 */
            readonly revision: number;
        } | {
            /** Format: int64 */
            readonly generation: number;
            /** Format: int64 */
            readonly head_seq: number;
            /** @enum {string} */
            readonly kind: "current_document_head";
        } | {
            /** Format: int32 */
            readonly actual: number;
            /** @enum {string} */
            readonly kind: "supported_schema";
            /** Format: int32 */
            readonly maximum: number;
            /** Format: int32 */
            readonly minimum: number;
        };
        readonly CoreModuleEventPayload: {
            readonly event: components["schemas"]["LibraryEvent"];
            /** @enum {string} */
            readonly module: "library";
        } | {
            readonly event: components["schemas"]["DatabaseEvent"];
            /** @enum {string} */
            readonly module: "database";
        } | {
            readonly event: components["schemas"]["OwnedDocumentEvent"];
            /** @enum {string} */
            readonly module: "owned_document";
        } | {
            readonly event: components["schemas"]["ProjectWorkspaceEvent"];
            /** @enum {string} */
            readonly module: "project_workspace";
        } | {
            readonly event: components["schemas"]["AutomationEvent"];
            /** @enum {string} */
            readonly module: "automation";
        } | {
            readonly event: components["schemas"]["StoreAdministrationEvent"];
            /** @enum {string} */
            readonly module: "store_administration";
        };
        /** @enum {string} */
        readonly CoreReadiness: "starting" | "ready" | "maintenance" | "failed";
        readonly DatabaseApplyRequest: components["schemas"]["ModuleApplyRequest_Vec_DatabaseIntent"];
        readonly DatabaseApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_DatabaseCommitValue_DatabaseReceipt"];
        readonly DatabaseEvent: {
            readonly data_source_ids: readonly string[];
            readonly database_ids: readonly string[];
            readonly kind: components["schemas"]["DatabaseEventKind"];
            readonly page_ids: readonly string[];
            readonly view_ids: readonly string[];
        };
        /** @enum {string} */
        readonly DatabaseEventKind: "database_changed";
        readonly DatabasePagePosition: {
            /** Format: int64 */
            readonly expected_position_revision: number;
            readonly page_id: string;
        };
        readonly DatabasePageValue: {
            readonly data_source_id: string;
            /** Format: int64 */
            readonly expected_value_revision: number;
            readonly page_id: string;
            readonly property_id: string;
            readonly value: unknown;
        };
        /** @enum {string} */
        readonly DatabaseReadMode: "catalog" | "database" | "data_source" | "view" | "query";
        readonly DatabaseReadRequest: components["schemas"]["ModuleReadRequest_DatabaseRead"];
        readonly DatabaseReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_DatabaseReadValue"];
        readonly DatabaseTarget: {
            /** @enum {string} */
            readonly kind: "project_default";
        } | {
            readonly database_id: string;
            /** @enum {string} */
            readonly kind: "database";
        } | {
            readonly data_source_id: string;
            /** @enum {string} */
            readonly kind: "data_source";
        } | {
            /** @enum {string} */
            readonly kind: "view";
            readonly view_id: string;
        };
        readonly DatabaseTransferTarget: {
            /** @enum {string} */
            readonly kind: "library";
            readonly library_id: string;
        } | {
            /** @enum {string} */
            readonly kind: "page";
            readonly page_id: string;
        } | {
            readonly data_source_id: string;
            /** @enum {string} */
            readonly kind: "data_source";
        };
        /** @enum {string} */
        readonly DeletableOwnedSourceKind: "synced_block" | "reusable_template";
        /** @enum {string} */
        readonly DocumentCommitOutcome: "committed" | "no_change";
        readonly DocumentHeadRevision: {
            readonly document_id: string;
            /** Format: int64 */
            readonly generation: number;
            /** Format: int64 */
            readonly head_seq: number;
        };
        /** @enum {string} */
        readonly DocumentInvalidationReason: "access_changed" | "generation_changed" | "restored";
        readonly DocumentOwnerCommand: {
            readonly before?: null | components["schemas"]["DocumentSpaceAnchor"];
            readonly document_id: string;
            readonly initial_blocks: readonly unknown[];
            /** @enum {string} */
            readonly kind: "create_synced_source";
            readonly source_block_id: string;
        } | {
            readonly host: components["schemas"]["DocumentHeadRevision"];
            /** @enum {string} */
            readonly kind: "promote_synced_source";
            readonly reference_block_id: string;
            readonly root_block_id: string;
            readonly source_block_id: string;
            readonly source_document_id: string;
        } | {
            readonly host: components["schemas"]["DocumentHeadRevision"];
            /** @enum {string} */
            readonly kind: "demote_synced_source";
            readonly reference_block_id: string;
            readonly source: components["schemas"]["DocumentHeadRevision"];
            readonly source_block_id: string;
        } | {
            readonly before?: null | components["schemas"]["DocumentSpaceAnchor"];
            readonly display_name: string;
            readonly document_id: string;
            readonly initial_blocks: readonly unknown[];
            /** @enum {string} */
            readonly kind: "create_template";
            readonly source_block_id: string;
        } | {
            readonly before_block_id?: string | null;
            /** @enum {string} */
            readonly kind: "instantiate_template";
            readonly parent_block_id?: string | null;
            readonly source: components["schemas"]["DocumentHeadRevision"];
            readonly source_block_id: string;
            readonly target: components["schemas"]["DocumentHeadRevision"];
        } | {
            /** @enum {string} */
            readonly kind: "delete_owned_source";
            readonly owner: components["schemas"]["DocumentOwnerRevision"];
            readonly owner_kind: components["schemas"]["DeletableOwnedSourceKind"];
        } | {
            readonly before?: null | components["schemas"]["DocumentSpaceAnchor"];
            readonly block_id: string;
            readonly display_name: string;
            readonly document_id: string;
            /** @enum {string} */
            readonly kind: "create_canvas_owner";
        } | {
            /** @enum {string} */
            readonly kind: "delete_canvas_owner";
            readonly owner: components["schemas"]["DocumentOwnerRevision"];
        };
        readonly DocumentOwnerEffect: {
            readonly created_block_ids: readonly string[];
            readonly deleted_block_ids: readonly string[];
            readonly document_heads: readonly components["schemas"]["DocumentHeadRevision"][];
            readonly preserved_block_ids: readonly string[];
        };
        readonly DocumentOwnerRevision: {
            readonly document_id: string;
            /** Format: int64 */
            readonly generation: number;
            /** Format: int64 */
            readonly head_seq: number;
            /** Format: int64 */
            readonly location_revision: number;
            /** Format: int64 */
            readonly metadata_revision: number;
            readonly owner_block_id: string;
        };
        readonly DocumentSemanticCommand: {
            readonly expected_etag: string;
            readonly inline_markdown: string;
            /** @enum {string} */
            readonly kind: "set_title";
        } | {
            /** @enum {string} */
            readonly kind: "patch_body";
            readonly new_fragment: string;
            readonly old_fragment: string;
        } | {
            readonly expected_etag: string;
            /** @enum {string} */
            readonly kind: "replace_body";
            readonly nested_markdown: string;
        } | {
            readonly block_id: string;
            /** @enum {string} */
            readonly kind: "delete_block";
        } | {
            readonly before_block_id?: string | null;
            readonly block_id: string;
            /** @enum {string} */
            readonly kind: "move_block";
            readonly parent_block_id?: string | null;
        };
        readonly DocumentSpaceAnchor: {
            readonly block_id: string;
            /** Format: int64 */
            readonly expected_location_revision: number;
        };
        readonly EventEnvelope: {
            readonly event: components["schemas"]["CommittedCoreModuleEvent"];
            /** Format: int32 */
            readonly protocol_version: number;
        };
        readonly HandshakeRequest: {
            readonly client: components["schemas"]["ClientIdentity"];
            readonly expected_profile_id?: string | null;
            readonly expected_start_nonce?: string | null;
            /** Format: int32 */
            readonly protocol_max: number;
            /** Format: int32 */
            readonly protocol_min: number;
        };
        readonly HandshakeResponse: {
            readonly build_id: string;
            /** Format: int64 */
            readonly event_head: number;
            readonly library_id: string;
            /** Format: int32 */
            readonly pid: number;
            readonly profile_id: string;
            /** Format: int32 */
            readonly protocol_version: number;
            /** Format: int32 */
            readonly schema_version: number;
            readonly start_nonce: string;
            readonly store_epoch: string;
        };
        readonly HealthResponse: {
            /** Format: int32 */
            readonly pid: number;
            readonly start_nonce: string;
            readonly status: components["schemas"]["CoreReadiness"];
        };
        /** @enum {string} */
        readonly LibraryAccess: "read" | "read_write";
        readonly LibraryApplyRequest: components["schemas"]["ModuleApplyRequest_LibraryIntent"];
        readonly LibraryApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_LibraryCommitValue_LibraryReceipt"];
        readonly LibraryCatalogEntry: {
            readonly kind: components["schemas"]["LibraryCatalogKind"];
            readonly lifecycle: components["schemas"]["LibraryLifecycle"];
            readonly location_label: string;
            /** Format: int64 */
            readonly location_revision: number;
            /** Format: int64 */
            readonly metadata_revision: number;
            readonly target: components["schemas"]["LibraryResourceTarget"];
            readonly title: string;
            readonly updated_at: string;
        };
        /** @enum {string} */
        readonly LibraryCatalogKind: "page" | "database";
        readonly LibraryEvent: {
            readonly database_ids: readonly string[];
            readonly kind: components["schemas"]["LibraryEventKind"];
            readonly page_ids: readonly string[];
            readonly parent_keys: readonly string[];
        };
        /** @enum {string} */
        readonly LibraryEventKind: "library_changed";
        /** @enum {string} */
        readonly LibraryLifecycle: "active" | "archived";
        readonly LibraryNavigationNode: {
            /** Format: int64 */
            readonly document_generation: number;
            /** Format: int64 */
            readonly document_head_seq: number;
            readonly has_children: boolean;
            /** @enum {string} */
            readonly kind: "page";
            /** Format: int64 */
            readonly metadata_revision: number;
            readonly page_id: string;
            /** Format: int64 */
            readonly parent_revision: number;
            readonly title: string;
            readonly updated_at: string;
        } | {
            readonly database_id: string;
            readonly default_view_id: string;
            readonly has_multiple_views: boolean;
            /** @enum {string} */
            readonly kind: "database";
            /** Format: int64 */
            readonly location_revision: number;
            /** Format: int64 */
            readonly metadata_revision: number;
            readonly title: string;
            readonly updated_at: string;
        } | {
            readonly data_source_id: string;
            readonly database_id: string;
            readonly is_default: boolean;
            /** @enum {string} */
            readonly kind: "view";
            /** Format: int64 */
            readonly revision: number;
            readonly title: string;
            readonly view_id: string;
            readonly view_kind: string;
        };
        readonly LibraryNavigationParent: {
            /** @enum {string} */
            readonly kind: "library";
        } | {
            /** @enum {string} */
            readonly kind: "page";
            readonly page_id: string;
        } | {
            readonly database_id: string;
            /** @enum {string} */
            readonly kind: "database";
        };
        readonly LibraryPlacementAnchor: {
            readonly block_id: string;
            /** Format: int64 */
            readonly expected_location_revision: number;
        };
        readonly LibraryReadRequest: components["schemas"]["ModuleReadRequest_LibraryRead"];
        readonly LibraryReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_LibraryReadValue"];
        readonly LibraryResourceTarget: {
            /** @enum {string} */
            readonly kind: "page";
            readonly page_id: string;
        } | {
            readonly database_id: string;
            /** @enum {string} */
            readonly kind: "database";
        };
        readonly LibraryRouteTarget: {
            /** @enum {string} */
            readonly kind: "page";
            readonly page_id: string;
        } | {
            readonly database_id: string;
            /** @enum {string} */
            readonly kind: "database";
        } | {
            /** @enum {string} */
            readonly kind: "view";
            readonly view_id: string;
        };
        readonly LibraryWriteParent: {
            readonly before?: null | components["schemas"]["LibraryPlacementAnchor"];
            /** @enum {string} */
            readonly kind: "library";
        } | {
            readonly before?: null | components["schemas"]["LibraryPlacementAnchor"];
            /** Format: int64 */
            readonly expected_document_generation: number;
            /** Format: int64 */
            readonly expected_document_head_seq: number;
            /** @enum {string} */
            readonly kind: "page";
            readonly page_id: string;
        };
        /** @enum {string} */
        readonly MaintenanceTask: "integrity_check" | "foreign_key_check" | "document_compaction" | "history_retention" | "block_retention";
        readonly ModuleApplyRequest_AutomationIntent: {
            readonly intent: {
                readonly definition: unknown;
                /** @enum {string} */
                readonly kind: "create_definition";
            } | {
                readonly definition: unknown;
                /** @enum {string} */
                readonly kind: "update_definition";
            } | {
                readonly automation_id: string;
                /** @enum {string} */
                readonly kind: "delete_definition";
            } | {
                readonly due_before: string;
                /** @enum {string} */
                readonly kind: "claim_due";
                /** Format: int64 */
                readonly lease_duration_ms: number;
                /** Format: int32 */
                readonly limit: number;
            } | {
                readonly completed_at: string;
                /** @enum {string} */
                readonly kind: "complete_lease";
                readonly lease_id: string;
            } | {
                readonly failed_at: string;
                /** @enum {string} */
                readonly kind: "fail_lease";
                readonly lease_id: string;
                readonly reason_code: string;
                readonly retry_at?: string | null;
            } | {
                /** @enum {string} */
                readonly kind: "complete_occurrence";
                readonly request: unknown;
            } | {
                /** @enum {string} */
                readonly kind: "update_occurrence";
                readonly request: unknown;
            } | {
                readonly consumed_at: string;
                /** @enum {string} */
                readonly kind: "consume_reminder";
                readonly reminder_id: string;
            } | {
                /** @enum {string} */
                readonly kind: "snooze_reminder";
                readonly reminder_id: string;
                readonly wake_at: string;
            };
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleApplyRequest_LibraryIntent: {
            readonly intent: {
                readonly document_id: string;
                /** @enum {string} */
                readonly kind: "create_page";
                readonly page_id: string;
                readonly parent: components["schemas"]["LibraryWriteParent"];
                readonly title: string;
            } | {
                readonly data_source_id: string;
                readonly database_id: string;
                /** @enum {string} */
                readonly kind: "create_database";
                readonly name: string;
                readonly parent: components["schemas"]["LibraryWriteParent"];
                readonly view_id: string;
            } | {
                /** Format: int64 */
                readonly expected_location_revision: number;
                /** @enum {string} */
                readonly kind: "move_block";
                readonly parent: components["schemas"]["LibraryWriteParent"];
                readonly target: components["schemas"]["LibraryResourceTarget"];
            } | {
                /** Format: int64 */
                readonly expected_metadata_revision: number;
                /** @enum {string} */
                readonly kind: "archive_resource";
                readonly target: components["schemas"]["LibraryResourceTarget"];
            } | {
                /** Format: int64 */
                readonly expected_metadata_revision: number;
                /** @enum {string} */
                readonly kind: "restore_resource";
                readonly target: components["schemas"]["LibraryResourceTarget"];
            } | {
                readonly access: components["schemas"]["LibraryAccess"];
                /** @enum {string} */
                readonly kind: "grant_project_access";
                readonly project_id: string;
                readonly target: components["schemas"]["LibraryResourceTarget"];
            };
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleApplyRequest_OwnedDocumentIntent: {
            readonly intent: {
                /** @enum {string} */
                readonly kind: "prepare_owner";
                readonly owner_block_id: string;
            } | {
                /** Format: int64 */
                readonly base_head_seq: number;
                readonly document_id: string;
                /** Format: int64 */
                readonly generation: number;
                /** @enum {string} */
                readonly kind: "apply_yjs_update";
                readonly touched_block_ids: readonly string[];
                readonly update: readonly number[];
                readonly update_id: string;
            } | {
                readonly commands: readonly components["schemas"]["DocumentSemanticCommand"][];
                readonly document_id: string;
                /** Format: int64 */
                readonly expected_head_seq: number;
                /** Format: int64 */
                readonly generation: number;
                /** @enum {string} */
                readonly kind: "apply_semantic_mutation";
            } | {
                readonly document_id: string;
                /** Format: int64 */
                readonly expected_head_seq: number;
                /** Format: int64 */
                readonly generation: number;
                /** @enum {string} */
                readonly kind: "apply_canvas_mutation";
                readonly mutation: unknown;
            } | {
                readonly cause: string;
                readonly document_id: string;
                /** Format: int64 */
                readonly expected_head_seq: number;
                /** Format: int64 */
                readonly generation: number;
                /** @enum {string} */
                readonly kind: "create_checkpoint";
                readonly label?: string | null;
            } | {
                readonly document_id: string;
                /** Format: int64 */
                readonly expected_head_seq: number;
                /** Format: int64 */
                readonly generation: number;
                /** @enum {string} */
                readonly kind: "restore_version";
                readonly version_id: string;
            } | {
                readonly command: components["schemas"]["DocumentOwnerCommand"];
                /** @enum {string} */
                readonly kind: "apply_owner_command";
            };
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleApplyRequest_ProjectWorkspaceIntent: {
            readonly intent: {
                readonly description: string;
                readonly icon?: string | null;
                /** @enum {string} */
                readonly kind: "create_project";
                readonly name: string;
                readonly project_id: string;
                readonly source_roots: readonly string[];
            } | {
                readonly description?: string | null;
                /** Format: int64 */
                readonly expected_binding_revision: number;
                readonly icon?: string | null;
                /** @enum {string} */
                readonly kind: "update_project";
                readonly name?: string | null;
                readonly project_id: string;
                readonly source_roots?: readonly string[] | null;
            } | {
                /** @enum {string} */
                readonly kind: "set_project_lifecycle";
                readonly lifecycle: components["schemas"]["ProjectLifecycle"];
                readonly project_id: string;
            } | {
                /** @enum {string} */
                readonly kind: "reorder_projects";
                readonly project_ids: readonly string[];
            } | {
                /** @enum {string} */
                readonly kind: "set_project_pinned";
                readonly pinned: boolean;
                readonly project_id: string;
            } | {
                readonly intent: components["schemas"]["ProjectSessionIntent"];
                /** @enum {string} */
                readonly kind: "mutate_session";
                readonly session_id: string;
            };
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleApplyRequest_StoreAdministrationIntent: {
            readonly intent: {
                readonly include_assets: boolean;
                /** @enum {string} */
                readonly kind: "create_backup";
                readonly label?: string | null;
            } | {
                readonly backup_id: string;
                readonly create_safety_backup: boolean;
                /** @enum {string} */
                readonly kind: "restore_backup";
            } | {
                readonly backup_id: string;
                /** @enum {string} */
                readonly kind: "delete_backup";
            } | {
                /** @enum {string} */
                readonly kind: "prune_backups";
                /** Format: int32 */
                readonly retain_count: number;
            } | {
                /** @enum {string} */
                readonly kind: "run_maintenance";
                readonly tasks: readonly components["schemas"]["MaintenanceTask"][];
            };
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleApplyRequest_Vec_DatabaseIntent: {
            readonly intent: readonly ({
                readonly before_property_id?: string | null;
                readonly data_source_id: string;
                /** Format: int64 */
                readonly expected_data_source_revision: number;
                /** Format: int64 */
                readonly expected_property_revision: number;
                /** @enum {string} */
                readonly kind: "put_property";
                readonly name: string;
                readonly property_id: string;
                readonly value_type: string;
            } | {
                readonly data_source_id: string;
                /** Format: int64 */
                readonly expected_data_source_revision: number;
                /** Format: int64 */
                readonly expected_property_revision: number;
                /** @enum {string} */
                readonly kind: "delete_property";
                readonly property_id: string;
            } | {
                readonly color?: string | null;
                readonly data_source_id: string;
                /** Format: int64 */
                readonly expected_property_revision: number;
                /** @enum {string} */
                readonly kind: "put_option";
                readonly name: string;
                readonly option_id: string;
                readonly property_id: string;
            } | {
                readonly data_source_id: string;
                /** Format: int64 */
                readonly expected_property_revision: number;
                /** @enum {string} */
                readonly kind: "delete_option";
                readonly option_id: string;
                readonly property_id: string;
            } | {
                readonly data_source_id: string;
                /** Format: int64 */
                readonly expected_value_revision: number;
                /** @enum {string} */
                readonly kind: "set_value";
                readonly page_id: string;
                readonly property_id: string;
                readonly value: unknown;
            } | {
                /** @enum {string} */
                readonly kind: "set_values";
                readonly values: readonly components["schemas"]["DatabasePageValue"][];
            } | {
                readonly add: readonly string[];
                readonly data_source_id: string;
                /** @enum {string} */
                readonly kind: "add_remove_value";
                readonly page_id: string;
                readonly property_id: string;
                readonly remove: readonly string[];
            } | {
                /** Format: int64 */
                readonly expected_active_membership_revision: number;
                /** Format: int64 */
                readonly expected_parent_revision: number;
                /** @enum {string} */
                readonly kind: "transfer_page";
                readonly page_id: string;
                readonly target: components["schemas"]["DatabaseTransferTarget"];
            } | {
                readonly before_view_id?: string | null;
                readonly config: unknown;
                readonly data_source_id: string;
                readonly database_id: string;
                /** Format: int64 */
                readonly expected_revision: number;
                readonly is_default: boolean;
                /** @enum {string} */
                readonly kind: "put_view";
                readonly name: string;
                readonly view_id: string;
                readonly view_kind: string;
            } | {
                readonly database_id: string;
                /** Format: int64 */
                readonly expected_revision: number;
                /** @enum {string} */
                readonly kind: "delete_view";
                readonly view_id: string;
            } | {
                readonly before_page_id?: string | null;
                /** Format: int64 */
                readonly expected_position_revision: number;
                readonly group_key?: string | null;
                /** @enum {string} */
                readonly kind: "position_page";
                readonly page_id: string;
                readonly view_id: string;
            } | {
                readonly before_page_id?: string | null;
                readonly group_key?: string | null;
                /** @enum {string} */
                readonly kind: "position_pages";
                readonly pages: readonly components["schemas"]["DatabasePagePosition"][];
                readonly view_id: string;
            })[];
            readonly operation_id: string;
            readonly store_epoch: components["schemas"]["StoreEpoch"];
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleMutationReceipt: {
            readonly duplicate: boolean;
            readonly operation_id: string;
        };
        readonly ModuleReadRequest_AutomationRead: {
            readonly read: {
                readonly include_deleted?: boolean | null;
                /** @enum {string} */
                readonly kind: "definitions";
            } | {
                readonly automation_id: string;
                /** @enum {string} */
                readonly kind: "definition";
            } | {
                /** @enum {string} */
                readonly kind: "runs_inbox";
                /** Format: int32 */
                readonly limit?: number | null;
            } | {
                /** @enum {string} */
                readonly kind: "occurrences";
                readonly project_id: string;
                readonly window_end: string;
                readonly window_start: string;
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleReadRequest_DatabaseRead: {
            readonly read: {
                readonly filter?: unknown;
                readonly mode: components["schemas"]["DatabaseReadMode"];
                readonly sort?: readonly unknown[] | null;
                readonly target: components["schemas"]["DatabaseTarget"];
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleReadRequest_LibraryRead: {
            readonly read: {
                /** @enum {string} */
                readonly kind: "metadata";
            } | {
                readonly cursor?: string | null;
                readonly force_include_target?: null | components["schemas"]["LibraryRouteTarget"];
                /** @enum {string} */
                readonly kind: "children";
                /** Format: int32 */
                readonly limit?: number | null;
                readonly parent: components["schemas"]["LibraryNavigationParent"];
            } | {
                /** @enum {string} */
                readonly kind: "path";
                readonly target: components["schemas"]["LibraryRouteTarget"];
            } | {
                readonly cursor?: string | null;
                /** @enum {string} */
                readonly kind: "catalog";
                readonly kinds?: readonly components["schemas"]["LibraryCatalogKind"][] | null;
                readonly lifecycle?: null | components["schemas"]["LibraryLifecycle"];
                /** Format: int32 */
                readonly limit?: number | null;
                readonly query?: string | null;
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleReadRequest_OwnedDocumentRead: {
            readonly read: {
                /** @enum {string} */
                readonly kind: "descriptor";
                readonly owner_block_id: string;
            } | {
                readonly document_id: string;
                /** @enum {string} */
                readonly kind: "sync_yjs";
                readonly state_vector: readonly number[];
            } | {
                readonly document_id: string;
                /** @enum {string} */
                readonly kind: "sync_canvas";
            } | {
                readonly before_version_id?: string | null;
                readonly document_id: string;
                /** @enum {string} */
                readonly kind: "list_versions";
                /** Format: int32 */
                readonly limit?: number | null;
            } | {
                readonly document_id: string;
                /** @enum {string} */
                readonly kind: "get_version";
                readonly version_id: string;
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleReadRequest_ProjectWorkspaceRead: {
            readonly read: {
                /** @enum {string} */
                readonly kind: "startup";
            } | {
                /** @enum {string} */
                readonly kind: "project";
                readonly project_id: string;
            } | {
                readonly include_archived?: boolean | null;
                /** @enum {string} */
                readonly kind: "sessions";
                readonly project_id?: string | null;
            } | {
                /** @enum {string} */
                readonly kind: "session";
                readonly session_id: string;
            } | {
                /** @enum {string} */
                readonly kind: "thread";
                readonly thread_id: string;
            } | {
                /** @enum {string} */
                readonly kind: "managed_worktrees";
                readonly project_id: string;
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly ModuleReadRequest_StoreAdministrationRead: {
            readonly read: {
                /** @enum {string} */
                readonly kind: "status";
            } | {
                /** @enum {string} */
                readonly kind: "backups";
            } | {
                /** @enum {string} */
                readonly kind: "maintenance_status";
            };
            /** Format: int32 */
            readonly version: number;
        };
        readonly OwnedDocumentApplyRequest: components["schemas"]["ModuleApplyRequest_OwnedDocumentIntent"];
        readonly OwnedDocumentApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_OwnedDocumentCommitValue_OwnedDocumentReceipt"];
        readonly OwnedDocumentEvent: {
            readonly document_id: string;
            /** Format: int64 */
            readonly generation: number;
            /** Format: int64 */
            readonly head_seq: number;
            /** @enum {string} */
            readonly kind: "document_updated";
            readonly update: readonly number[];
        } | {
            readonly document_id: string;
            /** Format: int64 */
            readonly generation: number;
            /** Format: int64 */
            readonly head_seq: number;
            /** @enum {string} */
            readonly kind: "canvas_updated";
            readonly mutation: unknown;
            readonly scene_hash: string;
        } | {
            readonly document_id: string;
            /** @enum {string} */
            readonly kind: "document_invalidated";
            readonly reason: components["schemas"]["DocumentInvalidationReason"];
        };
        readonly OwnedDocumentReadRequest: components["schemas"]["ModuleReadRequest_OwnedDocumentRead"];
        readonly OwnedDocumentReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_OwnedDocumentReadValue"];
        /** @enum {string} */
        readonly ProjectLifecycle: "active" | "inactive" | "archived";
        readonly ProjectSessionIntent: {
            /** @enum {string} */
            readonly kind: "rename";
            readonly title: string;
        } | {
            /** @enum {string} */
            readonly kind: "set_pinned";
            readonly pinned: boolean;
        } | {
            /** @enum {string} */
            readonly kind: "set_unread";
            readonly unread: boolean;
        } | {
            /** @enum {string} */
            readonly kind: "replace_panel_layout";
            readonly layout: unknown;
        } | {
            readonly config: unknown;
            /** @enum {string} */
            readonly kind: "create_tab";
            readonly panel_id: string;
            readonly tab_id: string;
            readonly title: string;
        } | {
            /** @enum {string} */
            readonly kind: "delete_tab";
            readonly tab_id: string;
        } | {
            readonly before_tab_id?: string | null;
            /** @enum {string} */
            readonly kind: "move_tab";
            readonly panel_id: string;
            readonly tab_id: string;
        } | {
            readonly expected_project_id?: string | null;
            /** @enum {string} */
            readonly kind: "link_thread";
            readonly thread_id: string;
        } | {
            /** @enum {string} */
            readonly kind: "unlink_thread";
            readonly thread_id: string;
        };
        readonly ProjectSource: {
            /** Format: int64 */
            readonly order: number;
            readonly root: string;
        };
        readonly ProjectWorkspaceApplyRequest: components["schemas"]["ModuleApplyRequest_ProjectWorkspaceIntent"];
        readonly ProjectWorkspaceApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_ProjectWorkspaceCommitValue_ProjectWorkspaceReceipt"];
        readonly ProjectWorkspaceEvent: {
            readonly kind: components["schemas"]["ProjectWorkspaceEventKind"];
            readonly project_ids: readonly string[];
            readonly session_ids: readonly string[];
            readonly thread_ids: readonly string[];
        };
        /** @enum {string} */
        readonly ProjectWorkspaceEventKind: "workspace_changed";
        readonly ProjectWorkspaceProject: {
            /** Format: int64 */
            readonly binding_revision: number;
            readonly created_at: string;
            readonly database_id: string;
            readonly description: string;
            readonly icon?: string | null;
            readonly id: string;
            readonly library_id: string;
            readonly lifecycle: components["schemas"]["ProjectLifecycle"];
            readonly name: string;
            readonly pinned: boolean;
            /** Format: int64 */
            readonly pinned_order?: number | null;
            readonly primary_workspace_root?: string | null;
            readonly sources: readonly components["schemas"]["ProjectSource"][];
            readonly updated_at: string;
        };
        readonly ProjectWorkspaceReadRequest: components["schemas"]["ModuleReadRequest_ProjectWorkspaceRead"];
        readonly ProjectWorkspaceReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_ProjectWorkspaceReadValue"];
        readonly ProjectWorkspaceSessionSummary: {
            readonly archived: boolean;
            readonly display_title: string;
            readonly id: string;
            /** Format: int64 */
            readonly order: number;
            readonly pinned: boolean;
            readonly project_id?: string | null;
            readonly thread_id?: string | null;
            readonly unread: boolean;
            readonly updated_at: string;
        };
        readonly ResponseEnvelope_CommittedModuleValue_AutomationCommitValue_AutomationReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly affected_automation_ids: readonly string[];
                    readonly affected_occurrence_ids: readonly string[];
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly affected_automation_ids: readonly string[];
                    readonly affected_occurrence_ids: readonly string[];
                    readonly claimed_leases: readonly components["schemas"]["AutomationLease"][];
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_CommittedModuleValue_DatabaseCommitValue_DatabaseReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly affected_data_source_ids: readonly string[];
                    readonly affected_database_ids: readonly string[];
                    readonly affected_page_ids: readonly string[];
                    readonly affected_view_ids: readonly string[];
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    /** Format: int32 */
                    readonly operation_count: number;
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_CommittedModuleValue_LibraryCommitValue_LibraryReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly affected_database_ids: readonly string[];
                    readonly affected_page_ids: readonly string[];
                    readonly affected_parent_keys: readonly string[];
                    readonly affected_view_ids: readonly string[];
                    /** Format: int64 */
                    readonly change_log_seq: number;
                    readonly committed_at: string;
                    readonly committed_revisions: {
                        readonly [key: string]: number;
                    };
                    readonly created_target?: null | components["schemas"]["LibraryResourceTarget"];
                    readonly did_mutate: boolean;
                    readonly operation_kind: string;
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly affected_resource_ids: readonly string[];
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_CommittedModuleValue_OwnedDocumentCommitValue_OwnedDocumentReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly document_id: string;
                    /** Format: int64 */
                    readonly generation: number;
                    /** Format: int64 */
                    readonly head_seq: number;
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly canvas?: unknown;
                    readonly document_id: string;
                    /** Format: int64 */
                    readonly generation: number;
                    /** Format: int64 */
                    readonly head_seq: number;
                    readonly outcome: components["schemas"]["DocumentCommitOutcome"];
                    readonly owner_effect?: null | components["schemas"]["DocumentOwnerEffect"];
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_CommittedModuleValue_ProjectWorkspaceCommitValue_ProjectWorkspaceReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly affected_project_ids: readonly string[];
                    readonly affected_session_ids: readonly string[];
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly affected_project_ids: readonly string[];
                    readonly affected_session_ids: readonly string[];
                    readonly affected_thread_ids: readonly string[];
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_CommittedModuleValue_StoreAdministrationCommitValue_StoreAdministrationReceipt: {
            readonly payload: {
                /** Format: int64 */
                readonly event_sequence: number;
                readonly receipt: components["schemas"]["ModuleMutationReceipt"] & {
                    readonly backup_id?: string | null;
                    readonly safety_backup_id?: string | null;
                };
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly backup_id?: string | null;
                    readonly completed_tasks: readonly components["schemas"]["MaintenanceTask"][];
                    readonly safety_backup_id?: string | null;
                };
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_AutomationReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly items: readonly unknown[];
                    /** @enum {string} */
                    readonly kind: "definitions";
                } | {
                    readonly item: unknown;
                    /** @enum {string} */
                    readonly kind: "definition";
                } | {
                    /** @enum {string} */
                    readonly kind: "runs_inbox";
                    readonly leases: readonly components["schemas"]["AutomationLease"][];
                } | {
                    /** @enum {string} */
                    readonly kind: "occurrences";
                    readonly occurrence_ids: readonly string[];
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_DatabaseReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly databases: readonly unknown[];
                    /** @enum {string} */
                    readonly kind: "catalog";
                } | {
                    /** @enum {string} */
                    readonly kind: "database";
                    readonly value: unknown;
                } | {
                    /** @enum {string} */
                    readonly kind: "data_source";
                    readonly value: unknown;
                } | {
                    /** @enum {string} */
                    readonly kind: "view";
                    readonly value: unknown;
                } | {
                    /** @enum {string} */
                    readonly kind: "query";
                    readonly value: unknown;
                } | {
                    /** @enum {string} */
                    readonly kind: "data_source_query";
                    readonly value: unknown;
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_LibraryReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    /** Format: int64 */
                    readonly change_log_seq: number;
                    /** @enum {string} */
                    readonly kind: "metadata";
                    readonly library_id: string;
                    readonly profile_id: string;
                } | {
                    readonly has_more: boolean;
                    readonly items: readonly components["schemas"]["LibraryNavigationNode"][];
                    /** @enum {string} */
                    readonly kind: "children";
                    readonly next_cursor?: string | null;
                    readonly parent: components["schemas"]["LibraryNavigationParent"];
                    /** Format: int64 */
                    readonly total: number;
                } | {
                    /** @enum {string} */
                    readonly kind: "path";
                    readonly nodes: readonly components["schemas"]["LibraryNavigationNode"][];
                    readonly target: components["schemas"]["LibraryRouteTarget"];
                } | {
                    readonly has_more: boolean;
                    readonly items: readonly components["schemas"]["LibraryCatalogEntry"][];
                    /** @enum {string} */
                    readonly kind: "catalog";
                    readonly next_cursor?: string | null;
                    /** Format: int64 */
                    readonly total: number;
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_OwnedDocumentReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly descriptor: unknown;
                    /** @enum {string} */
                    readonly kind: "descriptor";
                } | {
                    readonly descriptor: unknown;
                    /** @enum {string} */
                    readonly kind: "yjs_sync";
                    readonly update: readonly number[];
                } | {
                    readonly descriptor: unknown;
                    /** @enum {string} */
                    readonly kind: "canvas_sync";
                    readonly scene_hash: string;
                    readonly scene_json: readonly number[];
                } | {
                    readonly items: readonly unknown[];
                    /** @enum {string} */
                    readonly kind: "versions";
                    readonly next_version_id?: string | null;
                } | {
                    /** @enum {string} */
                    readonly kind: "version";
                    readonly value: unknown;
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_ProjectWorkspaceReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    /** @enum {string} */
                    readonly kind: "startup";
                    readonly projects: readonly components["schemas"]["ProjectWorkspaceProject"][];
                    readonly sessions: readonly components["schemas"]["ProjectWorkspaceSessionSummary"][];
                } | {
                    /** @enum {string} */
                    readonly kind: "project";
                    readonly project: components["schemas"]["ProjectWorkspaceProject"];
                } | {
                    /** @enum {string} */
                    readonly kind: "sessions";
                    readonly sessions: readonly components["schemas"]["ProjectWorkspaceSessionSummary"][];
                } | {
                    /** @enum {string} */
                    readonly kind: "session";
                    readonly panel_layout: unknown;
                    readonly session: components["schemas"]["ProjectWorkspaceSessionSummary"];
                } | {
                    /** @enum {string} */
                    readonly kind: "thread";
                    readonly project_id?: string | null;
                    readonly session_id?: string | null;
                    readonly thread_id: string;
                } | {
                    /** @enum {string} */
                    readonly kind: "managed_worktrees";
                    readonly roots: readonly string[];
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly ResponseEnvelope_ModuleReadSnapshot_StoreAdministrationReadValue: {
            readonly payload: {
                /** Format: int64 */
                readonly event_head: number;
                readonly store_epoch: components["schemas"]["StoreEpoch"];
                readonly value: {
                    readonly integrity: components["schemas"]["StoreIntegrity"];
                    /** @enum {string} */
                    readonly kind: "status";
                    readonly readiness: components["schemas"]["StoreReadiness"];
                    readonly schema_owner: components["schemas"]["SchemaOwner"];
                    /** Format: int32 */
                    readonly schema_version: number;
                } | {
                    readonly items: readonly components["schemas"]["BackupRecord"][];
                    /** @enum {string} */
                    readonly kind: "backups";
                } | {
                    readonly active: boolean;
                    /** @enum {string} */
                    readonly kind: "maintenance_status";
                    readonly operation_id?: string | null;
                    readonly phase?: string | null;
                };
                /** Format: int32 */
                readonly version: number;
            };
            /** @enum {string} */
            readonly status: "ok";
        } | {
            readonly payload: components["schemas"]["CoreError"];
            /** @enum {string} */
            readonly status: "error";
        };
        readonly RuntimeDescriptor: {
            readonly build_id: string;
            /** Format: int32 */
            readonly pid: number;
            readonly profile_id: string;
            /** Format: int32 */
            readonly protocol_max: number;
            /** Format: int32 */
            readonly protocol_min: number;
            /** Format: int64 */
            readonly readiness_generation: number;
            readonly socket_path: string;
            readonly start_nonce: string;
            readonly store_epoch: string;
        };
        /** @enum {string} */
        readonly SchemaOwner: "type_script" | "rust";
        readonly ShutdownResponse: {
            readonly status: components["schemas"]["ShutdownStatus"];
        };
        /** @enum {string} */
        readonly ShutdownStatus: "draining";
        readonly StoreAdministrationApplyRequest: components["schemas"]["ModuleApplyRequest_StoreAdministrationIntent"];
        readonly StoreAdministrationApplyResponse: components["schemas"]["ResponseEnvelope_CommittedModuleValue_StoreAdministrationCommitValue_StoreAdministrationReceipt"];
        readonly StoreAdministrationEvent: {
            readonly backup_ids: readonly string[];
            readonly kind: components["schemas"]["StoreAdministrationEventKind"];
            readonly operation: string;
            readonly readiness_changed: boolean;
        };
        /** @enum {string} */
        readonly StoreAdministrationEventKind: "store_administration_changed";
        readonly StoreAdministrationReadRequest: components["schemas"]["ModuleReadRequest_StoreAdministrationRead"];
        readonly StoreAdministrationReadResponse: components["schemas"]["ResponseEnvelope_ModuleReadSnapshot_StoreAdministrationReadValue"];
        readonly StoreEpoch: string;
        /** @enum {string} */
        readonly StoreIntegrity: "unknown" | "ok" | "failed";
        /** @enum {string} */
        readonly StoreReadiness: "starting" | "ready" | "maintenance" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly shutdown: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ShutdownResponse"];
                };
            };
        };
    };
    readonly events: {
        readonly parameters: {
            readonly query?: {
                /** @description Last committed event sequence observed */
                readonly after?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Server-sent committed Module events */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": components["schemas"]["EventEnvelope"];
                };
            };
        };
    };
    readonly handshake: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["HandshakeRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HandshakeResponse"];
                };
            };
        };
    };
    readonly health: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly administration_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StoreAdministrationApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StoreAdministrationApplyResponse"];
                };
            };
        };
    };
    readonly administration_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["StoreAdministrationReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StoreAdministrationReadResponse"];
                };
            };
        };
    };
    readonly automation_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AutomationApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AutomationApplyResponse"];
                };
            };
        };
    };
    readonly automation_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["AutomationReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AutomationReadResponse"];
                };
            };
        };
    };
    readonly database_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DatabaseApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DatabaseApplyResponse"];
                };
            };
        };
    };
    readonly database_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DatabaseReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DatabaseReadResponse"];
                };
            };
        };
    };
    readonly document_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OwnedDocumentApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OwnedDocumentApplyResponse"];
                };
            };
        };
    };
    readonly document_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OwnedDocumentReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OwnedDocumentReadResponse"];
                };
            };
        };
    };
    readonly library_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LibraryApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LibraryApplyResponse"];
                };
            };
        };
    };
    readonly library_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LibraryReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LibraryReadResponse"];
                };
            };
        };
    };
    readonly workspace_apply: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ProjectWorkspaceApplyRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProjectWorkspaceApplyResponse"];
                };
            };
        };
    };
    readonly workspace_read: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ProjectWorkspaceReadRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ProjectWorkspaceReadResponse"];
                };
            };
        };
    };
}
